### PR TITLE
Masonry: Set deployment target to iOS 8.0.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by StatusReport** [comment]
It seems you've set this to a subset of the targets (it's an addition and not modification of the project file).

**Comment by ghost** [comment]
Umm, is there any chance that there is a fallback if none is set in Xcode?

**Comment by StatusReport** [comment]
Nope, it is set there. Also make sure to set the `Unguarded Availability` to `Yes (All Versions)`.

**Comment by ghost** [comment]
Done. Verified `Unguarded Availability` set to `Yes`.

**Comment by StatusReport** [comment]
It should be `Yes (All Versions)` and not just `Yes`. Also why the deployment target is 8.4 and not 8.0?

**Comment by ghost** [comment]
1) OK.
2) 8.4 is the only iOS version that we saw had problems in Crashlytics. I don't mind setting it to 8. Of course iOS 8 will suffer from the same issues, yet no devices has been reported with such crashes.

**Comment by AmitYitzhack** [comment]
Ofcourse

**Comment by StatusReport** [comment]
1. Let's change to 8.
2. Do you see any compilation warnings now?

**Comment by ghost** [comment]
1. Done.
2. No.

**Pull request merged**
